// Карта сайта. Контент — templates/, общая разметка — templates/partials/.
export const SITE_ORIGIN = 'https://smarttech.asia';
export const pages = [
    { id: 'home', path: '/', group: 'home', heading: 'Системы безопасности для вашего объекта', headingKey: 'homeHeading',
      title: ['Системы безопасности в Астане — видеонаблюдение, СКУД, сигнализация | SmartTech', 'Астанадағы қауіпсіздік жүйелері | SmartTech', 'Security systems in Astana | SmartTech'],
      description: ['Видеонаблюдение, охранная сигнализация, турникеты, Face ID и интеграция систем. Подбор оборудования, монтаж и обслуживание в Астане и по Казахстану.', 'Астанада және Қазақстан бойынша бейнебақылау, күзет дабылы, турникеттер, Face ID, жүйелерді біріктіру және қызмет көрсету.', 'CCTV, security alarms, turnstiles, Face ID and system integration. Equipment selection, installation and support in Astana and across Kazakhstan.'], image: '/photos/1/IMG20260103124850-800.jpg' },
    { id: 'cctv', path: '/videonablyudenie/', group: 'services', heading: 'Видеонаблюдение', headingKey: 'feature1Title', intro: 'Подбираем камеры, запись, архив и обзор критичных зон объекта.', introKey: 'feature1Desc',
      title: ['Установка видеонаблюдения в Астане | SmartTech', 'Астанада бейнебақылау орнату | SmartTech', 'CCTV installation in Astana | SmartTech'],
      description: ['Подбор камер, монтаж, настройка записи и архива. Видеонаблюдение для бизнеса и жилых домов; отдельный комплект на этаж без абонентской платы.', 'Камераларды таңдау, орнату, жазба мен мұрағатты баптау. Бизнес пен тұрғын үйлерге арналған бейнебақылау.', 'Camera selection, installation, recording and archive setup for businesses and residential buildings. A separate floor CCTV package with no subscription.'] },
    { id: 'access', path: '/kontrol-dostupa/', group: 'services', heading: 'Турникеты и контроль доступа', headingKey: 'feature3Title', intro: 'Ставим турникеты, Face ID, карты доступа и учет проходов сотрудников и посетителей.', introKey: 'feature3Desc',
      title: ['Турникеты и Face ID Hikvision — комплекты СКУД в Астане | SmartTech', 'Hikvision турникеттері және Face ID — Астанадағы жиынтықтар | SmartTech', 'Hikvision turnstiles and Face ID packages in Astana | SmartTech'],
      description: ['Комплекты Hikvision START 3000, 6000 и 10000: турникет, 2 Face ID, монтаж и настройка. Модернизация действующих систем контроля доступа.', 'Hikvision START 3000, 6000 және 10000: турникет, 2 Face ID, орнату және баптау. Қолданыстағы жүйелерді жаңарту.', 'Hikvision START 3000, 6000 and 10000: a turnstile, two Face ID terminals, installation and setup. Upgrades for existing access systems.'], image: '/public/images/access-control/turnstile-hikvision-ds-k3g411.jpg' },
    { id: 'alarm', path: '/ohrannaya-signalizaciya/', group: 'services', heading: 'Охранная сигнализация', headingKey: 'feature2Title', intro: 'Настраиваем датчики, тревожные сценарии и уведомления по событиям.', introKey: 'feature2Desc',
      title: ['Охранная сигнализация в Астане — монтаж и настройка | SmartTech', 'Астанада күзет дабылын орнату | SmartTech', 'Security alarm installation in Astana | SmartTech'],
      description: ['Подбор датчиков и зон контроля, настройка тревожных сценариев и уведомлений. Согласуем состав системы и стоимость под ваш объект.', 'Датчиктер мен бақылау аймақтарын таңдау, дабыл сценарийлері мен хабарландыруларды баптау. Жүйе құрамы мен құнын нысаныңызға сай келісеміз.', 'Sensor and zone selection, alarm scenarios and notification setup. System scope and cost are agreed for your site.'] },
    { id: 'service', path: '/integraciya-i-servis/', group: 'services', heading: 'Интеграция и сервис', headingKey: 'feature4Title', intro: 'Связываем охранные системы между собой и с действующей инфраструктурой объекта.', introKey: 'feature4Desc',
      title: ['Интеграция и обслуживание систем безопасности | SmartTech', 'Қауіпсіздік жүйелерін біріктіру және қызмет көрсету | SmartTech', 'Security system integration and support | SmartTech'],
      description: ['Модернизация действующих систем, перенос пользователей, настройка интеграций и отчётов, сопровождение оборудования. Проверяем совместимость до начала работ.', 'Қолданыстағы жүйелерді жаңарту, пайдаланушыларды көшіру, интеграциялар мен есептерді баптау және жабдыққа қызмет көрсету.', 'Existing system upgrades, user migration, integrations, reporting and equipment support. Compatibility is checked before work begins.'] },
    { id: 'projects', path: '/proekty/', group: 'projects', heading: 'Выполненные проекты', headingKey: 'projectsPageTitle', intro: 'Примеры объектов, где мы усилили безопасность и сохранили действующую инфраструктуру', introKey: 'projectsSubtitle',
      title: ['Проекты SmartTech — контроль доступа и интеграция систем', 'SmartTech жобалары — қолжетімділікті бақылау және интеграция', 'SmartTech projects — access control and integration'],
      description: ['Кейсы SmartTech: КазУТБ, спортивный комплекс и общежитие. Задачи, установленное оборудование, результаты и реальные фотографии.', 'SmartTech жобалары: ҚазТБУ, спорт кешені және жатақхана. Міндеттер, жабдықтар, нәтижелер және нақты фотосуреттер.', 'SmartTech projects at KazUTB, a sports complex and a dormitory. Scope, equipment, outcomes and real installation photos.'], image: '/photos/1/IMG20260103124824-800.jpg' },
    { id: 'about', path: '/o-kompanii/', group: 'about', heading: 'О компании SmartTech', headingKey: 'aboutTitle', intro: 'Выезжаем на объект, подбираем решение, выполняем монтаж и сопровождаем систему после запуска.', introKey: 'companyIntro',
      title: ['О компании SmartTech — системы безопасности в Казахстане', 'SmartTech туралы — Қазақстандағы қауіпсіздік жүйелері', 'About SmartTech — security systems in Kazakhstan'],
      description: ['Подход SmartTech к проектированию, монтажу и обслуживанию систем безопасности. Этапы работы, партнёры и проекты компании.', 'SmartTech компаниясының қауіпсіздік жүйелерін жобалау, орнату және қызмет көрсету тәсілі. Жұмыс кезеңдері, серіктестер және жобалар.', 'How SmartTech plans, installs and supports security systems. Our process, partners and projects.'], image: '/photos/1/IMG20260103124850-800.jpg' },
    { id: 'contacts', path: '/kontakty/', group: 'contacts', heading: 'Контакты', headingKey: 'navContacts', intro: 'Астана • выезд по Казахстану', introKey: 'contactMeta3',
      title: ['Контакты SmartTech в Астане — обсудить объект', 'Астанадағы SmartTech байланыстары', 'Contact SmartTech in Astana'],
      description: ['Обсудите установку или модернизацию систем безопасности: WhatsApp и телефон +7 708 726 22 37, Instagram @smarttechastana. Астана и выезд по Казахстану.', 'Қауіпсіздік жүйелерін орнату немесе жаңартуды талқылаңыз: WhatsApp және телефон +7 708 726 22 37. Астана және Қазақстан бойынша шығу.', 'Discuss security system installation or upgrades: WhatsApp and phone +7 708 726 22 37, Instagram @smarttechastana. Based in Astana, serving Kazakhstan.'] }
];

export const legacyAnchors = {
    packages: '/kontrol-dostupa/#packages', modernization: '/kontrol-dostupa/#modernization',
    faq: '/kontrol-dostupa/#faq', capabilities: '/integraciya-i-servis/#capabilities',
    partners: '/o-kompanii/#partners', 'case-kazutb': '/proekty/#case-kazutb'
};
